/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WantedRouteImport } from './routes/wanted'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedFavouritesRouteImport } from './routes/_authenticated/favourites'
import { Route as AuthenticatedMyListingsRouteImport } from './routes/_authenticated/my-listings'
import { Route as AuthenticatedNewListingRouteImport } from './routes/_authenticated/new-listing'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedYourItemsRouteImport } from './routes/_authenticated/your-items'
import { Route as ItemsIdRouteImport } from './routes/items.$id'
import { Route as ListingsIndexRouteImport } from './routes/listings.index'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as AuthenticatedEditListingIdRouteImport } from './routes/_authenticated/edit-listing.$id'
import { Route as AuthenticatedOffersIndexRouteImport } from './routes/_authenticated/offers.index'
import { Route as AuthenticatedOffersIdRouteImport } from './routes/_authenticated/offers.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WantedRoute = WantedRouteImport.update({
  id: '/wanted',
  path: '/wanted',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavouritesRoute = AuthenticatedFavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyListingsRoute = AuthenticatedMyListingsRouteImport.update({
  id: '/my-listings',
  path: '/my-listings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewListingRoute = AuthenticatedNewListingRouteImport.update({
  id: '/new-listing',
  path: '/new-listing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedYourItemsRoute = AuthenticatedYourItemsRouteImport.update({
  id: '/your-items',
  path: '/your-items',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ItemsIdRoute = ItemsIdRouteImport.update({
  id: '/items/$id',
  path: '/items/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIndexRoute = ListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEditListingIdRoute =
  AuthenticatedEditListingIdRouteImport.update({
    id: '/edit-listing/$id',
    path: '/edit-listing/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOffersIndexRoute =
  AuthenticatedOffersIndexRouteImport.update({
    id: '/offers/',
    path: '/offers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOffersIdRoute = AuthenticatedOffersIdRouteImport.update({
  id: '/offers/$id',
  path: '/offers/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/wanted': typeof WantedRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/favourites': typeof AuthenticatedFavouritesRoute
  '/my-listings': typeof AuthenticatedMyListingsRoute
  '/new-listing': typeof AuthenticatedNewListingRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/your-items': typeof AuthenticatedYourItemsRoute
  '/items/$id': typeof ItemsIdRoute
  '/listings/$id': typeof ListingsIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/listings/': typeof ListingsIndexRoute
  '/edit-listing/$id': typeof AuthenticatedEditListingIdRoute
  '/offers/$id': typeof AuthenticatedOffersIdRoute
  '/offers/': typeof AuthenticatedOffersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/wanted': typeof WantedRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/favourites': typeof AuthenticatedFavouritesRoute
  '/my-listings': typeof AuthenticatedMyListingsRoute
  '/new-listing': typeof AuthenticatedNewListingRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/your-items': typeof AuthenticatedYourItemsRoute
  '/items/$id': typeof ItemsIdRoute
  '/listings/$id': typeof ListingsIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/listings': typeof ListingsIndexRoute
  '/edit-listing/$id': typeof AuthenticatedEditListingIdRoute
  '/offers/$id': typeof AuthenticatedOffersIdRoute
  '/offers': typeof AuthenticatedOffersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/wanted': typeof WantedRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/favourites': typeof AuthenticatedFavouritesRoute
  '/_authenticated/my-listings': typeof AuthenticatedMyListingsRoute
  '/_authenticated/new-listing': typeof AuthenticatedNewListingRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/your-items': typeof AuthenticatedYourItemsRoute
  '/items/$id': typeof ItemsIdRoute
  '/listings/$id': typeof ListingsIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/listings/': typeof ListingsIndexRoute
  '/_authenticated/edit-listing/$id': typeof AuthenticatedEditListingIdRoute
  '/_authenticated/offers/$id': typeof AuthenticatedOffersIdRoute
  '/_authenticated/offers/': typeof AuthenticatedOffersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcements'
    | '/auth'
    | '/help'
    | '/reset-password'
    | '/terms'
    | '/wanted'
    | '/admin'
    | '/favourites'
    | '/my-listings'
    | '/new-listing'
    | '/notifications'
    | '/settings'
    | '/your-items'
    | '/items/$id'
    | '/listings/$id'
    | '/profile/$username'
    | '/listings/'
    | '/edit-listing/$id'
    | '/offers/$id'
    | '/offers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/auth'
    | '/help'
    | '/reset-password'
    | '/terms'
    | '/wanted'
    | '/admin'
    | '/favourites'
    | '/my-listings'
    | '/new-listing'
    | '/notifications'
    | '/settings'
    | '/your-items'
    | '/items/$id'
    | '/listings/$id'
    | '/profile/$username'
    | '/listings'
    | '/edit-listing/$id'
    | '/offers/$id'
    | '/offers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/announcements'
    | '/auth'
    | '/help'
    | '/reset-password'
    | '/terms'
    | '/wanted'
    | '/_authenticated/admin'
    | '/_authenticated/favourites'
    | '/_authenticated/my-listings'
    | '/_authenticated/new-listing'
    | '/_authenticated/notifications'
    | '/_authenticated/settings'
    | '/_authenticated/your-items'
    | '/items/$id'
    | '/listings/$id'
    | '/profile/$username'
    | '/listings/'
    | '/_authenticated/edit-listing/$id'
    | '/_authenticated/offers/$id'
    | '/_authenticated/offers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AnnouncementsRoute: typeof AnnouncementsRoute
  AuthRoute: typeof AuthRoute
  HelpRoute: typeof HelpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  WantedRoute: typeof WantedRoute
  ItemsIdRoute: typeof ItemsIdRoute
  ListingsIdRoute: typeof ListingsIdRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  ListingsIndexRoute: typeof ListingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wanted': {
      id: '/wanted'
      path: '/wanted'
      fullPath: '/wanted'
      preLoaderRoute: typeof WantedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favourites': {
      id: '/_authenticated/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof AuthenticatedFavouritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-listings': {
      id: '/_authenticated/my-listings'
      path: '/my-listings'
      fullPath: '/my-listings'
      preLoaderRoute: typeof AuthenticatedMyListingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-listing': {
      id: '/_authenticated/new-listing'
      path: '/new-listing'
      fullPath: '/new-listing'
      preLoaderRoute: typeof AuthenticatedNewListingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/your-items': {
      id: '/_authenticated/your-items'
      path: '/your-items'
      fullPath: '/your-items'
      preLoaderRoute: typeof AuthenticatedYourItemsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/items/$id': {
      id: '/items/$id'
      path: '/items/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof ItemsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/': {
      id: '/listings/'
      path: '/listings'
      fullPath: '/listings/'
      preLoaderRoute: typeof ListingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/edit-listing/$id': {
      id: '/_authenticated/edit-listing/$id'
      path: '/edit-listing/$id'
      fullPath: '/edit-listing/$id'
      preLoaderRoute: typeof AuthenticatedEditListingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offers/': {
      id: '/_authenticated/offers/'
      path: '/offers'
      fullPath: '/offers/'
      preLoaderRoute: typeof AuthenticatedOffersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offers/$id': {
      id: '/_authenticated/offers/$id'
      path: '/offers/$id'
      fullPath: '/offers/$id'
      preLoaderRoute: typeof AuthenticatedOffersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedFavouritesRoute: typeof AuthenticatedFavouritesRoute
  AuthenticatedMyListingsRoute: typeof AuthenticatedMyListingsRoute
  AuthenticatedNewListingRoute: typeof AuthenticatedNewListingRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedYourItemsRoute: typeof AuthenticatedYourItemsRoute
  AuthenticatedEditListingIdRoute: typeof AuthenticatedEditListingIdRoute
  AuthenticatedOffersIdRoute: typeof AuthenticatedOffersIdRoute
  AuthenticatedOffersIndexRoute: typeof AuthenticatedOffersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedFavouritesRoute: AuthenticatedFavouritesRoute,
  AuthenticatedMyListingsRoute: AuthenticatedMyListingsRoute,
  AuthenticatedNewListingRoute: AuthenticatedNewListingRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedYourItemsRoute: AuthenticatedYourItemsRoute,
  AuthenticatedEditListingIdRoute: AuthenticatedEditListingIdRoute,
  AuthenticatedOffersIdRoute: AuthenticatedOffersIdRoute,
  AuthenticatedOffersIndexRoute: AuthenticatedOffersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AnnouncementsRoute: AnnouncementsRoute,
  AuthRoute: AuthRoute,
  HelpRoute: HelpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  WantedRoute: WantedRoute,
  ItemsIdRoute: ItemsIdRoute,
  ListingsIdRoute: ListingsIdRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  ListingsIndexRoute: ListingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
